### ISSUE TITLE
Serverless deploy with Sequelize Typescript

### ISSUE THREAD

**Issue by sandeepbussspacetech** [balassy/aws-lambda-typescript#112] opened 2018-11-30 06:20 UTC
Hello,

I build my project using the same farmwork and implement sequelize typescript for the data operation.

It's working fine with serverless offline.

but not working after deploy.

Thanks,

**Comment by balassy** [comment] 2018-12-02 12:50
Hello @sandeepbussspacetech ,
Could you please be more specific what "not working" exactly means?

**Comment by balassy** [comment] 2019-03-24 21:32
I close this because there is not enough information to reproduce the issue.

**Closed by balassy** 2019-03-24 21:32 UTC
